version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: languages
    ports:
      - 5432:5432
    volumes:
      - languages-db:/var/lib/postgresql/data
  api:
    build:
      context: .
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: languages
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - postgres
    ports:
      - 3000:3000
    restart: always

volumes:
  languages-db:
